-- Databricks notebook source
INSERT INTO
  SILVERDEV.DEFAULT.DM_POD (
    DAT,
    MES,
    DIA,
    NUM_DAT,
    NUM_ANO,
    NUM_MES,
    NUM_DIA,
    DSC_MES_ANO,
    DSC_MES_ANO_DIA,
    DSC_ABV_MES,
    DSC_ABV_MES_DIA,
    DSC_BIM,
    DSC_TRI,
    DSC_SEM,
    DSC_BIM_ANO,
    DSC_TRI_ANO,
    DSC_SEM_ANO,
    FLG_PRM_DIA,
    FLG_ULT_DIA,
    FLG_DIA_UTL,
    QTD_DIA_ANO,
    QTD_SEM_ANO,
    QTD_DIA_RST_ANO
  )
SELECT
  PER.DAT,
  PER.MES,
  PER.DIA,
  PER.NUM_DAT,
  PER.NUM_ANO,
  PER.NUM_MES,
  PER.NUM_DIA,
  PER.DSC_MES_ANO,
  PER.DSC_MES_ANO_DIA,
  PER.DSC_ABV_MES,
  PER.DSC_ABV_MES_DIA,
  PER.DSC_BIM,
  PER.DSC_TRI,
  PER.DSC_SEM,
  PER.DSC_BIM_ANO,
  PER.DSC_TRI_ANO,
  PER.DSC_SEM_ANO,
  PER.FLG_PRM_DIA,
  PER.FLG_ULT_DIA,
  PER.FLG_DIA_UTL,
  PER.QTD_DIA_ANO,
  PER.QTD_SEM_ANO,
  PER.QTD_DIA_RST_ANO
FROM
  BRONZEDEV.DEFAULT.PERIODO PER
  LEFT JOIN SILVERDEV.DEFAULT.DM_POD POD ON POD.DAT = PER.DAT
WHERE
  POD.DAT IS NULL;
