# Databricks notebook source
# DBTITLE 1,Create table dm_Est_Mat
# MAGIC %sql
# MAGIC drop table silverdev.default.dm_Est_Mat;
# MAGIC create table silverdev.default.dm_Est_Mat (
# MAGIC     COD_ESTAB bigint not null,
# MAGIC     NME_ESTAB string not null,
# MAGIC     NME_RAZ_SOC string not null,
# MAGIC     NUM_CNPJ string not null,
# MAGIC     NUM_CNPJ_MTRZ string not null,
# MAGIC     NME_CID string not null,
# MAGIC     NME_EST string not null,
# MAGIC     NME_END string not null,
# MAGIC     NME_BRRO string not null,
# MAGIC     NUM_CEP string not null,
# MAGIC     NUM_TEL string not null,
# MAGIC     DSC_EMAIL string not null,
# MAGIC     NME_SOC_PRP string not null,
# MAGIC     NUM_CPF_SOC_PRP string not null,
# MAGIC     NUM_AGC string not null,
# MAGIC     NUM_CTA_CORR string not null,
# MAGIC     DAT_CAD_ESTAB date not null,
# MAGIC     DAT_VAL_CNPJ date not null,
# MAGIC     SRK_ESTAB_MATRIZ bigint generated by default as identity not null,
# MAGIC     PRIMARY KEY (SRK_ESTAB_MATRIZ)
# MAGIC );
# MAGIC
