# Databricks notebook source
# DBTITLE 1,Create table d_pod
CREATE TABLE SILVERDEV.default.DM_POD (
    SRK_DAT BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    DAT date,
    MES string,
    DIA string,
    NUM_DAT string,
    NUM_ANO int,
    NUM_MES int,
    NUM_DIA int,
    DSC_MES_ANO string,
    DSC_MES_ANO_DIA string,
    DSC_ABV_MES string,
    DSC_ABV_MES_DIA string,
    DSC_BIM string,
    DSC_TRI string,
    DSC_SEM string,
    DSC_BIM_ANO string,
    DSC_TRI_ANO string,
    DSC_SEM_ANO string,
    FLG_PRM_DIA int,
    FLG_ULT_DIA int,
    FLG_DIA_UTL INT,
    QTD_DIA_ANO int,
    QTD_SEM_ANO int,
    QTD_DIA_RST_ANO int,
    PRIMARY KEY (SRK_DAT)
);
