# Databricks notebook source
# DBTITLE 1,Create table dm_Usu
# MAGIC %sql
# MAGIC drop table silverdev.default.dm_Usu;
# MAGIC create table silverdev.default.dm_Usu (
# MAGIC     COD_PRP_PF bigint not null,
# MAGIC     NUM_CPF string not null,
# MAGIC     DAT_NASC date not null,
# MAGIC     DSC_NAC string not null,
# MAGIC     NUM_DEP bigint not null,
# MAGIC     DSC_EST_CIV string not null,
# MAGIC     DSC_SEX string not null,
# MAGIC     DSC_NAT string not null,
# MAGIC     DSC_EML string not null,
# MAGIC     DSC_END string not null,
# MAGIC     DSC_BRRO string not null,
# MAGIC     DSC_CID string not null,
# MAGIC     DSC_EST string not null,
# MAGIC     NUM_CEP string,
# MAGIC     DSC_TIP_RES string not null,
# MAGIC     NUM_TEL01 string not null,
# MAGIC     TIP_TEL01 string not null,
# MAGIC     NUM_TEL02 string not null,
# MAGIC     TIP_TEL02 string not null,
# MAGIC     FLG_CPF_VAL integer not null,
# MAGIC     CEP_LIMP string,
# MAGIC     BAI_NO_BAI string,
# MAGIC     LOC_NO_LOC string,
# MAGIC     LOG_NU_LOG string,
# MAGIC     UFE_SG_LOG string,
# MAGIC     BAI_NU_INI_LOG string,
# MAGIC     BAI_NU_FIM_LOG string,
# MAGIC     LOG_NO_LOG string,
# MAGIC     LOG_COMPLEMENTO_LOG string,
# MAGIC     CEP_LOG string,
# MAGIC     TLO_TX_LOG string,
# MAGIC     LOG_STA_TLO_LOG string,
# MAGIC     LOG_NO_ABREV_LOG string,
# MAGIC     SRK_USUARIO bigint generated by default as identity not null,
# MAGIC     PRIMARY KEY (SRK_USUARIO)
# MAGIC );
# MAGIC
