# Databricks notebook source
# DBTITLE 1,Create table f_Trn_Usu
# MAGIC %sql
# MAGIC drop table silverdev.default.f_Trn_Usu;
# MAGIC create table silverdev.default.f_Trn_Usu (
# MAGIC     COD_TRN bigint not null,
# MAGIC     SRK_DAT_MOV_AUT bigint not null,
# MAGIC     SRK_ESTAB_FILIAL bigint not null,
# MAGIC     SRK_ESTAB_MATRIZ bigint not null,
# MAGIC     SRK_CLI bigint not null,
# MAGIC     SRK_USUARIO bigint not null, 
# MAGIC     SRK_TIP_PRD bigint not null,
# MAGIC     COD_TIP_TRN string not null,
# MAGIC     COD_MEI_CPT string not null,
# MAGIC     COD_RDE string not null,
# MAGIC     COD_EST string not null, 
# MAGIC     COD_PRD string not null,
# MAGIC     COD_DISTR string not null,
# MAGIC     COD_EMP string not null,
# MAGIC     --COD_VINC_TRN string not null,
# MAGIC     COD_CTO_EMV string not null,
# MAGIC     COD_ESTAB_MIGR string not null,
# MAGIC     COD_MOD_ENT string not null,
# MAGIC     COD_TIP_MSG string not null,
# MAGIC     COD_PROV string not null,
# MAGIC     COD_STA_CTR string not null,
# MAGIC     COD_TCBN_REF string not null,
# MAGIC     COD_TRN_CONTEST string not null,
# MAGIC     NUM_PARC string not null,
# MAGIC     NUM_AUT string not null,
# MAGIC     NUM_TERM string not null,
# MAGIC     NUM_HR_LOC string not null,
# MAGIC     NUM_LOT string not null,
# MAGIC     NUM_REF_TRN string not null,
# MAGIC     NUM_SENH_CAPTUR string not null,
# MAGIC     DAT_LOC bigint not null,
# MAGIC     SRK_DAT_GMT bigint not null,
# MAGIC     SRK_DAT_AUT bigint not null,
# MAGIC     SRK_DAT_SOL bigint not null,
# MAGIC     SRK_DAT_REPASS bigint not null,
# MAGIC     VAL_COMP float not null,
# MAGIC     VAL_TXA_JUR float not null,
# MAGIC     VAL_TRN float not null,
# MAGIC     VAL_COMP_FORM_GEN float not null,
# MAGIC     VAL_PGTO_MIN float not null,
# MAGIC     VAL_CMSS float not null,
# MAGIC     FLG_FBCK string not null,
# MAGIC     NSU_ORIG string not null,
# MAGIC     FLG_TAR string not null,
# MAGIC     ID_TRN string not null,
# MAGIC     SRK_TRN bigint generated by default as identity not null,
# MAGIC     PRIMARY KEY (SRK_TRN)
# MAGIC );
# MAGIC

# COMMAND ----------

# MAGIC %sql
# MAGIC select * from silverdev.default.f_Trn_Usu;
